### PR TITLE
Switch from debian:jessie to Alpine Linux

### PR DESCRIPTION
**Pull request by benoitvidis**
Refactor of the containers to use [Alpine Linux](http://www.alpinelinux.org/) as base image.

:warning: **NB1: Once this PR is merged, the docker-compose file for Kuzzle need to be modified to use the new kuzzle/test image.**
:warning: **NB2: Once/if adopted, the alpine tag should be removed from the build chain and Docker hub updated accordingly.**

### Details

* `base`: includes the minimal tools to run the application. 
Remark: bash is not installed but symlinked to ash for user convenience (i.e. to run `docker run -ti kuzzleio/kuzzle bash`)
* `test`: inherits from base. Includes dependencies for npm
* `dev`: inherits from test. Includes the development tools (shells & vim mainly)
* `bo-base`: inherits from base. Adds sass compiler & bower (@todo: refactor to move them to the bo-test layer).
* `bo-test`: inherits from bo-base. Adds some additional dependencies for bower & the run-test.sh script and phantomjs.
* `bo-dev`: inherits form bo-test. Provides some development tools.
* `elasticsearch`: Elastic 2.2 :warning: ES 1.7 was not ported. Can only be used once Kuzzle migrates to ES2.2
* `rabbitmq`: Embeds the STOMP & MQTT plugins. Note the management plugin has been removed from the previous version.

### Test branches

project | branch | travis build
----------|----------|---------
kuzzle | [alpine](https://github.com/kuzzleio/kuzzle/tree/alpine) | https://travis-ci.org/kuzzleio/kuzzle/builds/115359964
kuzzle-bo | [alpine](https://github.com/kuzzleio/kuzzle-bo/tree/alpine) | https://travis-ci.org/kuzzleio/kuzzle-bo/builds/115853250

### CODE REVIEW

**Comment by stafyniaksacha** [comment]
Yay ! :+1:

**Comment by dbengsch** [comment]
+1

**Comment by scottinet** [comment]
+1

**Comment by benoitvidis** [comment]
:warning: *DO NOT MERGE*

After discussion, it appears the master branch must be kept as-is to preserve some backward compatibility with older Kuzzle(bo) releases.

**Pull request closed without merging**
