### PR TITLE
ES: Disable the ES GeoIP downloader by default

### PR DESCRIPTION
**Pull request by Kuruyia**
## What does this PR do ?
This disables the ES GeoIP downloader by setting the `ingest.geoip.downloader.enabled` environment variable to `false` in the Dockerfile of the elasticsearch container.

This is done to move this environment variable out of the docker-compose file of Kuzzle applications and template.

### CODE REVIEW

**Comment by Aschen** [comment]
Fix https://github.com/kuzzleio/kuzzle-containers/issues/70

**Review by Aschen — APPROVED** [review]
Ensure the new image is builded and pushed to Dockerhub. You can ask help from @alexandrebouthinon

**Review by alexandrebouthinon — APPROVED** [review]
LGTM 👍 Just pushed a new CI/CD Workflow to build and deploy automatically on Dockerhub when committing on master

**Review by Shiranuit — APPROVED** [review]

**Comment by Aschen** [comment]
@Kuruyia I let you merge this and ensure that the new image is then available on Dockerhub :+1:

**Review by rolljee — APPROVED** [review]

**Pull request merged**
